language: scala
jdk: openjdk8
env:
  matrix:
    # Test with the defaults
    - SCRIPT="sbt new file://$(pwd) '--name=Hello World' && cd hello-world && sbt test"
    # Test with custom name/organization to ensure templating is done correctly
    - SCRIPT="sbt new file://$(pwd) --name=smello --organization=org.eggsample && cd smello && sbt test"
script: eval "$SCRIPT"
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2aa0aeda88d31fe293d4
    on_success: change
    on_failure: always
    on_start: never
